int a, b, c;
char letra;
float x;
double y;
void referencia;
boolean flag;
int numero = 10;
int n1 = 1, n2 = 2, n3 = 3;
float media = 7.5;
double taxa = 2.25;
float x1 = 1.1, x2 = 2.2;
char inicial = 'a';
char c1 = 'x', c2 = 'y';
boolean ativo = true;
boolean ok = true, feito = false;
char codigo = 65;
boolean errado = 1;
int misto = 1, texto = 'x';
void v = 10;